
SINGLE_STRING_BEGIN_END_REGEX = r"\'"
SINGLE_STRING_ESCAPE_REGEX = r"\\\'"
SINGLE_STRING_CONTENT_REGEX = r"[^']"

DOUBLE_STRING_BEGIN_END_REGEX = r'\"'
DOUBLE_STRING_ESCAPE_REGEX = r'\\\"'
DOUBLE_STRING_CONTENT_REGEX = r'[^"]'